'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import type { OfferPayload, AnswerPayload, IceCandidatePayload } from '@/types/call.types';

const ICE_SERVERS: RTCIceServer[] = [
  { urls: ['stun:stun.l.google.com:19302', 'stun:stun1.l.google.com:19302'] },
];

type MediaStatus = 'idle' | 'acquiring' | 'ready' | 'denied';

interface UseWebRTCOptions {
  onSendOffer: (offer: RTCSessionDescriptionInit) => void;
  onSendAnswer: (answer: RTCSessionDescriptionInit) => void;
  onSendIceCandidate: (candidate: RTCIceCandidateInit) => void;
  onConnected: () => void;
  onFailed: () => void;
}

export function useWebRTC({
  onSendOffer,
  onSendAnswer,
  onSendIceCandidate,
  onConnected,
  onFailed,
}: UseWebRTCOptions) {
  const [localStream, setLocalStream] = useState<MediaStream | null>(null);
  const [remoteStream, setRemoteStream] = useState<MediaStream | null>(null);
  const [mediaStatus, setMediaStatus] = useState<MediaStatus>('idle');
  const [cameraOn, setCameraOn] = useState(true);
  const [micOn, setMicOn] = useState(true);

  const pcRef = useRef<RTCPeerConnection | null>(null);
  const localStreamRef = useRef<MediaStream | null>(null);
  const iceCandidatesQueueRef = useRef<RTCIceCandidateInit[]>([]);
  const hasRemoteDescriptionRef = useRef<boolean>(false);

  // Keep callback references fresh
  const callbacksRef = useRef({
    onSendOffer,
    onSendAnswer,
    onSendIceCandidate,
    onConnected,
    onFailed,
  });

  useEffect(() => {
    callbacksRef.current = {
      onSendOffer,
      onSendAnswer,
      onSendIceCandidate,
      onConnected,
      onFailed,
    };
  });

  // ── Get user media ──────────────────────────────────────────────────────────
  useEffect(() => {
    let isMounted = true;
    setMediaStatus('acquiring');

    navigator.mediaDevices
      .getUserMedia({ video: true, audio: true })
      .then((stream) => {
        if (!isMounted) {
          stream.getTracks().forEach((t) => t.stop());
          return;
        }
        setLocalStream(stream);
        localStreamRef.current = stream;
        setMediaStatus('ready');
      })
      .catch((err) => {
        console.error('getUserMedia error:', err);
        if (isMounted) {
          setMediaStatus('denied');
          callbacksRef.current.onFailed();
        }
      });

    return () => {
      isMounted = false;
      localStreamRef.current?.getTracks().forEach((t) => t.stop());
      localStreamRef.current = null;
    };
  }, []);

  // ── Flush queued ICE candidates ─────────────────────────────────────────────
  const flushQueuedCandidates = useCallback(async () => {
    if (!pcRef.current || !hasRemoteDescriptionRef.current) return;
    const queue = [...iceCandidatesQueueRef.current];
    iceCandidatesQueueRef.current = [];

    for (const candidate of queue) {
      try {
        await pcRef.current.addIceCandidate(new RTCIceCandidate(candidate));
      } catch (err) {
        console.warn('Error adding queued ICE candidate:', err);
      }
    }
  }, []);

  // ── Create or get existing PeerConnection ───────────────────────────────────
  const getOrCreatePeerConnection = useCallback((): RTCPeerConnection => {
    if (pcRef.current && pcRef.current.signalingState !== 'closed') {
      return pcRef.current;
    }

    const pc = new RTCPeerConnection({ iceServers: ICE_SERVERS });
    pcRef.current = pc;
    hasRemoteDescriptionRef.current = false;
    iceCandidatesQueueRef.current = [];

    // Add local tracks to peer connection
    if (localStreamRef.current) {
      localStreamRef.current.getTracks().forEach((track) => {
        pc.addTrack(track, localStreamRef.current!);
      });
    }

    // Handle receiving remote tracks
    pc.ontrack = (event) => {
      if (event.streams && event.streams[0]) {
        setRemoteStream(event.streams[0]);
      } else {
        setRemoteStream((prev) => {
          const stream = prev ?? new MediaStream();
          stream.addTrack(event.track);
          return new MediaStream(stream.getTracks());
        });
      }
    };

    // Handle ICE candidates generated by local peer
    pc.onicecandidate = (event) => {
      if (event.candidate) {
        callbacksRef.current.onSendIceCandidate(event.candidate.toJSON());
      }
    };

    // Monitor connection status
    pc.onconnectionstatechange = () => {
      console.log('[WebRTC] Connection state:', pc.connectionState);
      if (pc.connectionState === 'connected') {
        callbacksRef.current.onConnected();
      } else if (pc.connectionState === 'failed' || pc.connectionState === 'disconnected') {
        callbacksRef.current.onFailed();
      }
    };

    return pc;
  }, []);

  // ── Initiate call (create offer) ────────────────────────────────────────────
  const initiateCall = useCallback(async () => {
    try {
      const pc = getOrCreatePeerConnection();
      const offer = await pc.createOffer({
        offerToReceiveAudio: true,
        offerToReceiveVideo: true,
      });
      await pc.setLocalDescription(offer);
      callbacksRef.current.onSendOffer(offer);
      console.log('[WebRTC] Created and sent offer');
    } catch (err) {
      console.error('[WebRTC] initiateCall error:', err);
    }
  }, [getOrCreatePeerConnection]);

  // ── Handle incoming offer ───────────────────────────────────────────────────
  const handleOffer = useCallback(
    async ({ offer }: OfferPayload) => {
      try {
        const pc = getOrCreatePeerConnection();
        await pc.setRemoteDescription(new RTCSessionDescription(offer));
        hasRemoteDescriptionRef.current = true;
        await flushQueuedCandidates();

        const answer = await pc.createAnswer();
        await pc.setLocalDescription(answer);
        callbacksRef.current.onSendAnswer(answer);
        console.log('[WebRTC] Handled offer and sent answer');
      } catch (err) {
        console.error('[WebRTC] handleOffer error:', err);
      }
    },
    [getOrCreatePeerConnection, flushQueuedCandidates],
  );

  // ── Handle incoming answer ──────────────────────────────────────────────────
  const handleAnswer = useCallback(
    async ({ answer }: AnswerPayload) => {
      try {
        if (!pcRef.current) return;
        await pcRef.current.setRemoteDescription(new RTCSessionDescription(answer));
        hasRemoteDescriptionRef.current = true;
        await flushQueuedCandidates();
        console.log('[WebRTC] Handled answer');
      } catch (err) {
        console.error('[WebRTC] handleAnswer error:', err);
      }
    },
    [flushQueuedCandidates],
  );

  // ── Handle ICE candidate ────────────────────────────────────────────────────
  const handleIceCandidate = useCallback(
    async ({ candidate }: IceCandidatePayload) => {
      try {
        if (
          pcRef.current &&
          hasRemoteDescriptionRef.current &&
          pcRef.current.remoteDescription
        ) {
          await pcRef.current.addIceCandidate(new RTCIceCandidate(candidate));
        } else {
          iceCandidatesQueueRef.current.push(candidate);
        }
      } catch (err) {
        console.warn('[WebRTC] handleIceCandidate error:', err);
      }
    },
    [],
  );

  // ── Camera toggle ───────────────────────────────────────────────────────────
  const toggleCamera = useCallback(() => {
    localStreamRef.current?.getVideoTracks().forEach((t) => {
      t.enabled = !t.enabled;
    });
    setCameraOn((prev) => !prev);
  }, []);

  // ── Mic toggle ──────────────────────────────────────────────────────────────
  const toggleMic = useCallback(() => {
    localStreamRef.current?.getAudioTracks().forEach((t) => {
      t.enabled = !t.enabled;
    });
    setMicOn((prev) => !prev);
  }, []);

  // ── Hang up ─────────────────────────────────────────────────────────────────
  const hangUp = useCallback(() => {
    hasRemoteDescriptionRef.current = false;
    iceCandidatesQueueRef.current = [];
    pcRef.current?.close();
    pcRef.current = null;
    localStreamRef.current?.getTracks().forEach((t) => t.stop());
    localStreamRef.current = null;
    setLocalStream(null);
    setRemoteStream(null);
  }, []);

  return {
    localStream,
    remoteStream,
    mediaStatus,
    cameraOn,
    micOn,
    initiateCall,
    handleOffer,
    handleAnswer,
    handleIceCandidate,
    toggleCamera,
    toggleMic,
    hangUp,
  };
}
